# Generated by Django 3.0.8 on 2020-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='опис')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='фото для слайдеру')),
            ],
            options={
                'verbose_name': 'Слайдер',
            },
        ),
    ]
