# Generated by Django 3.0.8 on 2020-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=15, verbose_name='час')),
                ('short_description', models.CharField(max_length=125, verbose_name='короткий опис')),
                ('description', models.TextField(verbose_name='опис')),
            ],
            options={
                'verbose_name': 'захід в програмі',
                'verbose_name_plural': 'Програма',
            },
        ),
    ]
