# Generated by Django 3.0.8 on 2020-08-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'Категорія продукції',
                'verbose_name_plural': 'Категорії продукції',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='назва альбому')),
                ('category', models.CharField(choices=[('fest', 'Фестиваль'), ('event', 'Захід'), ('product', 'Продукція')], max_length=15, verbose_name='категорія альбому')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='title/', verbose_name='титульне фото')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='опис альбому')),
                ('is_title', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True, verbose_name='створено')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереї',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name="ім'я")),
                ('last_name', models.CharField(max_length=125, verbose_name='прізвище')),
                ('image', models.ImageField(upload_to='master/', verbose_name='фото')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='фейсбук')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='інстаграм')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='сайт')),
                ('category', models.ManyToManyField(blank=True, related_name='masters', to='event.CategoryProduct')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_master', to='event.Gallery')),
            ],
            options={
                'verbose_name': 'Майстер',
                'verbose_name_plural': 'Майстри',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d', verbose_name='фото')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.Gallery', verbose_name='галерея')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
            },
        ),
    ]
