# Generated by Django 3.0.8 on 2020-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_categoryproduct_gallery_imagegallery_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='повний опис'),
        ),
        migrations.AddField(
            model_name='master',
            name='short_description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='короткий опис'),
        ),
    ]
