# Generated by Django 3.0.8 on 2020-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200805_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фейсбук'),
        ),
        migrations.AlterField(
            model_name='master',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='інстаграм'),
        ),
        migrations.AlterField(
            model_name='master',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='сайт'),
        ),
    ]
