# Generated by Django 3.0.8 on 2020-08-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200805_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, verbose_name='назва')),
                ('image', models.ImageField(upload_to='sponsor/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсори',
            },
        ),
    ]
