# Generated by Django 3.0.8 on 2020-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Короткий опис')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='фото')),
                ('is_approve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
    ]
