# Generated by Django 3.0.8 on 2020-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='назва заходу')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='місце проведення')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='дата проведення')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Час і місце',
            },
        ),
    ]
