# Generated by Django 3.0.8 on 2020-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_sponsor_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name="ім'я")),
                ('last_name', models.CharField(max_length=125, verbose_name='прізвище')),
                ('image', models.ImageField(upload_to='manager/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджери',
            },
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['id'], 'verbose_name': 'Фото галереї', 'verbose_name_plural': 'Фото галереї'},
        ),
    ]
