# Generated by Django 3.0.8 on 2020-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200817_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='middle_name',
            field=models.CharField(default='', max_length=125, verbose_name='по -батькові'),
        ),
    ]
