# Generated by Django 3.0.8 on 2020-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_manager_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткий опис товару')),
                ('description', models.TextField(blank=True, verbose_name='Опис товару')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пропозиція активна')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='event.CategoryProduct', verbose_name='Категорія')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_product', to='event.Gallery')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Master', verbose_name='майстер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
